@baseUrl = http://localhost:3000

###
# 1) CRIAR 
POST {{baseUrl}}/users
Content-Type: application/json

{
  "nome": "Sidney",
  "email": "Sindeycardosojo@gmail.com",
  "senha": "12345"
}

###
# 2) LISTAR 
GET {{baseUrl}}/users

###
# 3) LER 
GET {{baseUrl}}/users/5

###
# 4) ATUALIZAR 
PUT {{baseUrl}}/users/5
Content-Type: application/json

{
  "nome": "Sidney Cardoso atualziado",
  "senha": "1234567"
}

###
# 5) EXCLUIR 
DELETE {{baseUrl}}/users/5
